// automatically generated by the FlatBuffers compiler, do not modify

using System;
using FlatBuffers;

public struct LoginReq : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static LoginReq GetRootAsLoginReq(ByteBuffer _bb) { return GetRootAsLoginReq(_bb, new LoginReq()); }
  public static LoginReq GetRootAsLoginReq(ByteBuffer _bb, LoginReq obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public LoginReq __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Account { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetAccountBytes() { return __p.__vector_as_arraysegment(4); }
  public string Platform { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetPlatformBytes() { return __p.__vector_as_arraysegment(6); }
  public string Channel { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetChannelBytes() { return __p.__vector_as_arraysegment(8); }

  public static Offset<LoginReq> CreateLoginReq(FlatBufferBuilder builder,
      StringOffset accountOffset = default(StringOffset),
      StringOffset platformOffset = default(StringOffset),
      StringOffset channelOffset = default(StringOffset)) {
    builder.StartObject(3);
    LoginReq.AddChannel(builder, channelOffset);
    LoginReq.AddPlatform(builder, platformOffset);
    LoginReq.AddAccount(builder, accountOffset);
    return LoginReq.EndLoginReq(builder);
  }

  public static void StartLoginReq(FlatBufferBuilder builder) { builder.StartObject(3); }
  public static void AddAccount(FlatBufferBuilder builder, StringOffset accountOffset) { builder.AddOffset(0, accountOffset.Value, 0); }
  public static void AddPlatform(FlatBufferBuilder builder, StringOffset platformOffset) { builder.AddOffset(1, platformOffset.Value, 0); }
  public static void AddChannel(FlatBufferBuilder builder, StringOffset channelOffset) { builder.AddOffset(2, channelOffset.Value, 0); }
  public static Offset<LoginReq> EndLoginReq(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<LoginReq>(o);
  }
  public static void FinishLoginReqBuffer(FlatBufferBuilder builder, Offset<LoginReq> offset) { builder.Finish(offset.Value); }
};

